Usando el archivo `datos.csv` resuelva las siguientes preguntas. Para los cálculos use el lenguage Python. El archivo contiene 10 variables independientes y una variable de salida. No todas las variables independientes son relevantes. La variable de salida indica la clase a la que pertenece cada uno de los ejemplos.

# Pregunta 1

Si se usa un algoritmo de detección de grupos (como k-means), el algoritmo es capaz de detectar los grupos existentes y asignar correctamente los registros a cada grupo? Podría escogerse un subconjunto de variables independientes para mejorar la detección de grupos? argumente.

Los algoritmos de detección de grupos o clusters utilizan un aprendizaje no supervisado. Esto quiere decir que no se definen unas clases predefinidas como variable respuesta para él clasificar en dichas clases, sino que es capaz de detectar los grupos o clusters presentes en una muestra y asignar correctamente los registros pertenecientes a cada grupo. Algunas de las variables independientes pueden tener ruido que haga que la detección de grupos sea peor, por lo que se puede escoger un subconjunto de ellas con el fin mejorar la detección. Adicionalmente, es necesario seleccionar las variables más relevantes para garantizar parsimonia. Lo primero, es calcular el modelo:

In [1]:
#Carga de las librerias necesarias
import pandas as pd
import numpy as np
import os
from sklearn.cluster import KMeans


#Selección del directorio de trabajo
os.chdir('/home/agch2/Dropbox/Asignaturas 2017-I MIS/Aprendizaje de maquinas/machine-learning-master')

#Carga del archivo en un dataframe
df = pd.read_table("datos.csv",sep=",")

#Selección de variables independientes y dependiente (la última no es usada para calibrar el modelo sino solo para ver que tal pronostica, ya que es un algoritmo no supervisado)
indep=df.iloc[:,range(10)]
depend=np.array(df.loc[:,"class"], dtype=int)

#Ajuste del modelo:
kmeans = KMeans(n_clusters=3, random_state=0).fit(indep)
kmeans.labels_
kmeans.cluster_centers_
kmeans_predict=kmeans.predict(indep)
kmeans_predict

kmeans_predict[kmeans_predict==2]=[3]
kmeans_predict[kmeans_predict==0]=[4]
kmeans_predict[kmeans_predict==1]=[5]
kmeans_predict=kmeans_predict-2
kmeans_predict

#Rendimiento del modelo:
rend_Km=np.mean(depend==kmeans_predict)
rend_Km

ImportError: No module named 'pandas'

Se puede observar que la predicción del modelo es de un 100%. Ahora procedemos a seleccionar las variables principales. K-means no cuenta con una función para la selección de variables y la función SelectFromModel, la cual es utilizada en otros algoritmos como regresión logística y árboles de desición, no funciona para k-means ya que este clasificador no permite la obtención de sus parámetros. Así, se realiza la selección de variables de la siguiente forma:

- Se aplica el algoritmo añadiendo una por una cada variable independiente. Es decir, se empieza utilizando solamente una de ellas y luego se utiliza otra, extrayendo la variable incluida anteriormente. Esto se hace sucesivamente para cada una de las variables. De todas las variables, finalmente la primera variable que se incluye en el modelo, es quella que mayor aumento genera en su rendimiento.
- El procedimiento anterior se hace repetidamente hasta que el rendimiento se estabilice.

In [35]:
rend_tot_fin=[]
S_F_tot=[]
V_S_F=range(indep.shape[1])
indep2=indep[:]


for j in range(indep.shape[1]):  #Ver como cambia el rendimiento mientras aumento una por una mis variables

    rend_tot=[]
    
    for i in V_S_F:  #Selecionar la variable que genera mayor aumento en el rendimiento de cada corrida
        
        if j==0:
            indep_F_S=indep.iloc[:,[i]]
        else:
            indep_F_S=indep.iloc[:,list(set().union(S_F_tot,[i]))]
            
        #print(list(set().union(seq1,seq2)))
        #print(indep_F_S)

        kmeans = KMeans(n_clusters=3, random_state=0).fit(indep_F_S)
        kmeans.labels_
        kmeans.cluster_centers_
        kmeans_predict=kmeans.predict(indep_F_S)
        #kmeans_predict

        kmeans_predict[kmeans_predict==2]=[3]
        kmeans_predict[kmeans_predict==0]=[4]
        kmeans_predict[kmeans_predict==1]=[5]
        kmeans_predict=kmeans_predict-2
        #kmeans_predict

        rend_Km=np.mean(depend==kmeans_predict)
        #rend_Km
        #print("%.3f" % rend_Km)

        rend_tot.append(rend_Km)

    print(rend_tot)
    m = max(rend_tot)
    S_F=[i for i, j in enumerate(rend_tot) if j == m]
    if j==0:
        S_F=S_F[:]
    else:
        for k in S_F_tot:
            if S_F[0]>=k:
                S_F[0]=S_F[0]+1
            else: S_F[0]=S_F[0]
    S_F_tot.append(S_F[0])
    
    seq1=list(range(indep2.shape[1]))[0:S_F[0]]
    seq2=list(range(indep2.shape[1]))[S_F[0]+1:10]
    V_S_F=list(set().union(seq1,seq2))
    indep2=indep2.iloc[:,V_S_F]
    #print(V_S_F)
    
    rend_tot_fin.append(m)

#print(rend_tot_fin)

m2 = max(rend_tot_fin)
S_F_Max=[i for i, j in enumerate(rend_tot_fin) if j == m2]

S_F_Variables=S_F_tot[0:S_F_Max[0]+1]
print("Variables seleccionadas:   ","x",S_F_Variables[0],",   x",S_F_Variables[1],"\nRendimiento:",m2)

[0.68666666666666665, 0.35999999999999999, 0.32666666666666666, 0.32444444444444442, 0.71333333333333337, 0.65111111111111108, 0.36222222222222222, 0.33111111111111113, 0.3288888888888889, 0.18222222222222223]
[1.0, 0.71777777777777774, 0.61777777777777776, 0.18222222222222223, 0.58444444444444443, 0.62, 0.14888888888888888, 0.71111111111111114, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0]
Variables seleccionadas:    x 4 ,   x 0 
Rendimiento: 1.0


In [36]:
df

x1        x2        x3        x4        x5        x6        x7  \
0    0.217051  2.301448  2.063373 -2.877469 -0.280745  3.037343  1.523219   
1    0.245344  1.873901  2.177668 -2.907616  0.539491  3.113836  1.327698   
2    0.515188  2.052923  2.021482 -2.868717 -0.211045  3.082855  1.517711   
3    0.529766  1.793446  2.211673 -2.912831  0.281599  3.107664  1.510040   
4    0.821210  1.472261  2.057228 -2.733129 -0.566706  3.071136  1.462961   
5    0.006832  1.636809  2.006419 -3.058976 -0.320725  3.001691  1.342740   
6    0.210622  1.673330  2.118072 -2.981704 -0.725106  3.026343  1.441529   
7   -0.926146  1.261560  2.006528 -2.930952  0.484750  2.796875  1.414336   
8   -0.519451  1.875428  2.189321 -2.811001 -0.945430  2.944155  1.465402   
9    0.154951  2.140579  2.288953 -3.041501 -0.305526  3.018264  1.332776   
10  -0.302194  2.050196  2.138238 -3.014728 -0.374175  2.898792  1.362273   
11  -0.428108  1.680516  2.062366 -2.895603 -0.660615  2.915524  1.545691   
12  -0.452245  2.424376  2.016694 -3.038602  0.396414  2.877719  1.336798   
13  -0.108509  2.012992  2.119065 -2.946988 -0.720570  3.038645  1.395422   
14  -0.784852  2.450662  2.211342 -3.134406 -0.437385  2.761676  1.402790   
15  -0.147035  2.439806  2.201525 -2.825718 -0.390904  2.957382  1.343200   
16   0.932146  2.384470  2.298470 -3.062080  0.306889  3.202696  1.338564   
17   0.098343  2.410916  2.059060 -2.846657 -1.096217  2.994067  1.463084   
18   0.407787  2.272680  2.150172 -3.058024 -0.531482  3.150858  1.423009   
19  -0.209380  2.479509  2.226240 -2.989601 -0.553719  3.008934  1.414875   
20  -0.141683  1.302622  2.092771 -2.941385  0.392647  3.024554  1.365461   
21   0.007407  1.369037  2.284265 -2.971157  0.611643  3.023738  1.339219   
22   0.553244  2.215524  2.094046 -2.819657 -0.749271  3.122881  1.353810   
23  -0.821321  1.639603  2.020876 -2.919568  0.015265  2.852100  1.419129   
24   0.030722  2.055849  2.065461 -2.968292 -0.330598  2.971950  1.600525   
25  -0.425451  2.058847  2.146603 -2.945560  0.084463  2.897839  1.507799   
26  -0.948557  2.128176  2.022100 -2.991530 -0.712736  2.799983  1.470865   
27  -0.596753  1.677890  2.136021 -2.958481 -0.362574  2.907057  1.451998   
28  -0.250969  1.618797  2.152137 -3.329180 -0.276166  2.909922  1.338413   
29  -0.631126  1.952123  2.062024 -3.063278 -0.912259  2.845517  1.232254   
..        ...       ...       ...       ...       ...       ...       ...   
420  1.249536  1.846241  2.070209 -2.927690  3.929507  3.323305  1.295185   
421 -0.083256  2.132653  2.294562 -2.901698  3.989392  2.973411  1.313637   
422 -0.592756  1.800851  2.281936 -3.130621  3.596956  3.013814  1.402944   
423  1.056286  2.006616  2.135334 -3.315864  4.871020  3.146246  1.202127   
424  1.139059  2.197716  2.093532 -3.037180  3.680993  3.130567  1.315892   
425  0.372909  1.810888  2.265692 -3.146839  4.706296  3.100160  1.472112   
426 -0.529953  2.164506  2.090126 -2.975108  3.914228  2.941962  1.504100   
427  0.235931  1.567985  2.067270 -2.895951  4.153225  3.082652  1.331822   
428 -0.358486  2.217774  2.278658 -3.120664  4.689749  2.862759  1.388073   
429  0.187761  2.588326  2.004511 -2.985296  4.112142  2.986820  1.396137   
430 -0.328706  2.329890  2.014622 -2.884776  3.400428  2.904493  1.465519   
431 -0.459310  2.243127  2.242724 -2.968291  4.137557  2.975686  1.461761   
432  0.461500  2.172727  2.044540 -3.017665  4.533970  3.059462  1.374882   
433  0.655876  2.801924  2.067437 -3.033931  4.285524  3.163496  1.445800   
434  0.837600  2.207080  2.269473 -2.883769  4.075764  3.222426  1.398534   
435 -0.029511  1.973159  2.006542 -3.057832  3.663763  2.966326  1.379871   
436  0.609322  2.369980  2.068103 -3.159087  4.210023  3.186490  1.360216   
437  0.052223  2.123672  2.072466 -3.034055  4.176275  2.929346  1.328129   
438  1.051514  2.726953  2.053192 -3.191931  3.844498  3.384465  1.312509   
439 -0.547267  2.001009  2.039908 -2.905683  4.119493  2.836192  1.360827   
440 -0.

Con la variable x4 y x0 obtenemos el 100% de rendimiento en el modelo.

# Pregunta 2

Constuya un sistema clasificador que permita asignar un nuevo punto a una de las tres clases. El clasificador debe usar internamente la regresión logística. Es posible detectar las variables relevantes independientes usando regresión  logística? 

Para utilizar la Regresión Logística se utilizan 3 clasificadores, debido a que la variable dependiente tiene 3 clases. Dado que ninguna de las variables independientes son categóricas, estas se trabajan como decimales. Se normalizan las variables para que el modelo ajuste correctamente.

In [37]:
#Carga de las librerias necesarias
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel

#Creación de las tres nuevas columnas las cuales son las variables dependientes de los 3 modelos (3 clasificadores  a partir de la regresión logistica)
df.insert(df.shape[1], "C1", ([0] * len(df)))
df.loc[df.iloc[:,(df.shape[1]-2)]==1,"C1"]=[1]

df.insert(df.shape[1], "C2", ([0] * len(df)))
df.loc[df.iloc[:,(df.shape[1]-3)]==2,"C2"]=[1]

df.insert(df.shape[1], "C3", ([0] * len(df)))
df.loc[df.iloc[:,(df.shape[1]-4)]==3,"C3"]=[1]

#Selección de variables independientes y dependientes de los 3 modelos (referentes a las 3 clases de la variable respueta)
indep=df.iloc[:,range(10)]
depend1=np.array(df.loc[:,"C1"], dtype=str)
depend2=np.array(df.loc[:,"C2"], dtype=str)
depend3=np.array(df.loc[:,"C3"], dtype=str)

#Normalizacion de variables
indep = (indep - indep.mean()) / (indep.max() - indep.min())

In [38]:
df

x1        x2        x3        x4        x5        x6        x7  \
0    0.217051  2.301448  2.063373 -2.877469 -0.280745  3.037343  1.523219   
1    0.245344  1.873901  2.177668 -2.907616  0.539491  3.113836  1.327698   
2    0.515188  2.052923  2.021482 -2.868717 -0.211045  3.082855  1.517711   
3    0.529766  1.793446  2.211673 -2.912831  0.281599  3.107664  1.510040   
4    0.821210  1.472261  2.057228 -2.733129 -0.566706  3.071136  1.462961   
5    0.006832  1.636809  2.006419 -3.058976 -0.320725  3.001691  1.342740   
6    0.210622  1.673330  2.118072 -2.981704 -0.725106  3.026343  1.441529   
7   -0.926146  1.261560  2.006528 -2.930952  0.484750  2.796875  1.414336   
8   -0.519451  1.875428  2.189321 -2.811001 -0.945430  2.944155  1.465402   
9    0.154951  2.140579  2.288953 -3.041501 -0.305526  3.018264  1.332776   
10  -0.302194  2.050196  2.138238 -3.014728 -0.374175  2.898792  1.362273   
11  -0.428108  1.680516  2.062366 -2.895603 -0.660615  2.915524  1.545691   
12  -0.452245  2.424376  2.016694 -3.038602  0.396414  2.877719  1.336798   
13  -0.108509  2.012992  2.119065 -2.946988 -0.720570  3.038645  1.395422   
14  -0.784852  2.450662  2.211342 -3.134406 -0.437385  2.761676  1.402790   
15  -0.147035  2.439806  2.201525 -2.825718 -0.390904  2.957382  1.343200   
16   0.932146  2.384470  2.298470 -3.062080  0.306889  3.202696  1.338564   
17   0.098343  2.410916  2.059060 -2.846657 -1.096217  2.994067  1.463084   
18   0.407787  2.272680  2.150172 -3.058024 -0.531482  3.150858  1.423009   
19  -0.209380  2.479509  2.226240 -2.989601 -0.553719  3.008934  1.414875   
20  -0.141683  1.302622  2.092771 -2.941385  0.392647  3.024554  1.365461   
21   0.007407  1.369037  2.284265 -2.971157  0.611643  3.023738  1.339219   
22   0.553244  2.215524  2.094046 -2.819657 -0.749271  3.122881  1.353810   
23  -0.821321  1.639603  2.020876 -2.919568  0.015265  2.852100  1.419129   
24   0.030722  2.055849  2.065461 -2.968292 -0.330598  2.971950  1.600525   
25  -0.425451  2.058847  2.146603 -2.945560  0.084463  2.897839  1.507799   
26  -0.948557  2.128176  2.022100 -2.991530 -0.712736  2.799983  1.470865   
27  -0.596753  1.677890  2.136021 -2.958481 -0.362574  2.907057  1.451998   
28  -0.250969  1.618797  2.152137 -3.329180 -0.276166  2.909922  1.338413   
29  -0.631126  1.952123  2.062024 -3.063278 -0.912259  2.845517  1.232254   
..        ...       ...       ...       ...       ...       ...       ...   
420  1.249536  1.846241  2.070209 -2.927690  3.929507  3.323305  1.295185   
421 -0.083256  2.132653  2.294562 -2.901698  3.989392  2.973411  1.313637   
422 -0.592756  1.800851  2.281936 -3.130621  3.596956  3.013814  1.402944   
423  1.056286  2.006616  2.135334 -3.315864  4.871020  3.146246  1.202127   
424  1.139059  2.197716  2.093532 -3.037180  3.680993  3.130567  1.315892   
425  0.372909  1.810888  2.265692 -3.146839  4.706296  3.100160  1.472112   
426 -0.529953  2.164506  2.090126 -2.975108  3.914228  2.941962  1.504100   
427  0.235931  1.567985  2.067270 -2.895951  4.153225  3.082652  1.331822   
428 -0.358486  2.217774  2.278658 -3.120664  4.689749  2.862759  1.388073   
429  0.187761  2.588326  2.004511 -2.985296  4.112142  2.986820  1.396137   
430 -0.328706  2.329890  2.014622 -2.884776  3.400428  2.904493  1.465519   
431 -0.459310  2.243127  2.242724 -2.968291  4.137557  2.975686  1.461761   
432  0.461500  2.172727  2.044540 -3.017665  4.533970  3.059462  1.374882   
433  0.655876  2.801924  2.067437 -3.033931  4.285524  3.163496  1.445800   
434  0.837600  2.207080  2.269473 -2.883769  4.075764  3.222426  1.398534   
435 -0.029511  1.973159  2.006542 -3.057832  3.663763  2.966326  1.379871   
436  0.609322  2.369980  2.068103 -3.159087  4.210023  3.186490  1.360216   
437  0.052223  2.123672  2.072466 -3.034055  4.176275  2.929346  1.328129   
438  1.051514  2.726953  2.053192 -3.191931  3.844498  3.384465  1.312509   
439 -0.547267  2.001009  2.039908 -2.905683  4.119493  2.836192  1.360827   
440 -0.

In [40]:
#Ajuste de cada uno de los modelos
model1 = LogisticRegression(fit_intercept = True, C = 1e100)
mdl1 = model1.fit(indep, depend1)

model2 = LogisticRegression(fit_intercept = True, C = 1e100)
mdl2 = model2.fit(indep, depend2)

model3 = LogisticRegression(fit_intercept = True, C = 1e100)
mdl3 = model3.fit(indep, depend3)


#Predicción de cada uno de los modelos
predicted_1 = model1.predict(indep)
predicted_2 = model2.predict(indep)
predicted_3 = model3.predict(indep)


#Rendimiento de cada uno de los modelos
rend1=np.mean(depend1==predicted_1)
rend2=np.mean(depend2==predicted_2)
rend3=np.mean(depend3==predicted_3)

depend1=np.array(depend1, dtype=float)
depend2=np.array(depend2, dtype=float)
depend3=np.array(depend3, dtype=float)

#Rendimiento del modelo global
print("Rendimiento del modelo global:",(depend1.sum()*rend1+depend2.sum()*rend2+depend3.sum()*rend3)/indep.shape[0])

predicted_2

Rendimiento del modelo global: 1.0


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

Ahora se seleccionan las variables más importantes de cada uno de los modelos mediante la función SelectFromModel. Esto, debido a que cada uno de los clasificadores puede seleccionar variables diferentes.

In [5]:
model1_sf = SelectFromModel(model1, prefit=True)
indep1_new = model1_sf.transform(indep)

model2_sf = SelectFromModel(model2, prefit=True)
indep2_new = model2_sf.transform(indep)

model3_sf = SelectFromModel(model3, prefit=True)
indep3_new = model3_sf.transform(indep)

print("Variables independientes iniciales:   ",indep.shape[1],
      "\nVariables independientes seleccionadas:   ",indep1_new.shape[1])
print("Variables independientes iniciales:   ",indep.shape[1],
      "\nVariables independientes seleccionadas:   ",indep2_new.shape[1])
print("Variables independientes iniciales:   ",indep.shape[1],
      "\nVariables independientes seleccionadas:   ",indep3_new.shape[1])

print(indep1_new,
indep2_new,
indep3_new)

Variables independientes iniciales:    10 
Variables independientes seleccionadas:    3
Variables independientes iniciales:    10 
Variables independientes seleccionadas:    4
Variables independientes iniciales:    10 
Variables independientes seleccionadas:    4
[[-0.1392571  -0.23496336 -0.28978407]
 [-0.13449675 -0.11559366 -0.20473017]
 [-0.08909405 -0.22481985 -0.24223321]
 ..., 
 [-0.09864033  0.39669125  0.24812936]
 [-0.00932399  0.31928561  0.23812691]
 [-0.11849727  0.35555569  0.18120497]] [[-0.1392571  -0.23496336 -0.13876086 -0.28978407]
 [-0.13449675 -0.11559366 -0.07656122 -0.20473017]
 [-0.08909405 -0.22481985 -0.10175362 -0.24223321]
 ..., 
 [-0.09864033  0.39669125 -0.09012874  0.24812936]
 [-0.00932399  0.31928561 -0.08967742  0.23812691]
 [-0.11849727  0.35555569 -0.05566866  0.18120497]] [[-0.1392571  -0.23496336 -0.13876086 -0.28978407]
 [-0.13449675 -0.11559366 -0.07656122 -0.20473017]
 [-0.08909405 -0.22481985 -0.10175362 -0.24223321]
 ..., 
 [-0.09864033  0.396

De los 3 clasificadores, 1 de ellos seleccionó 2 variables, mientras que los otros 2 seleccionaron estas mismas 3 y un adicional. Así, puede decirse que el clasificador global considera 4 variables importantes:

In [6]:
indep3_new

array([[-0.1392571 , -0.23496336, -0.13876086, -0.28978407],
       [-0.13449675, -0.11559366, -0.07656122, -0.20473017],
       [-0.08909405, -0.22481985, -0.10175362, -0.24223321],
       ..., 
       [-0.09864033,  0.39669125, -0.09012874,  0.24812936],
       [-0.00932399,  0.31928561, -0.08967742,  0.23812691],
       [-0.11849727,  0.35555569, -0.05566866,  0.18120497]])

In [7]:
indep

x1        x2        x3        x4        x5        x6        x7  \
0   -0.139257  0.143554 -0.282084  0.205907 -0.234963 -0.138761  0.305083   
1   -0.134497 -0.093457  0.100915  0.157693 -0.115594 -0.076561 -0.163231   
2   -0.089094  0.005784 -0.422460  0.219904 -0.224820 -0.101754  0.291890   
3   -0.086641 -0.138058  0.214865  0.149352 -0.153125 -0.081580  0.273516   
4   -0.037604 -0.316107 -0.302678  0.436753 -0.276579 -0.111283  0.160753   
5   -0.174628 -0.224890 -0.472938 -0.084380 -0.240782 -0.167751 -0.127202   
6   -0.140339 -0.204644 -0.098790  0.039202 -0.299632 -0.147706  0.109419   
7   -0.331606 -0.432909 -0.472572  0.120372 -0.123560 -0.334296  0.044286   
8   -0.263177 -0.092610  0.139966  0.312211 -0.331696 -0.214536  0.166601   
9   -0.149706  0.054376  0.473831 -0.056431 -0.238570 -0.154275 -0.151067   
10  -0.226623  0.004272 -0.031213 -0.013612 -0.248560 -0.251423 -0.080414   
11  -0.247809 -0.200660 -0.285461  0.176905 -0.290246 -0.237818  0.358908   
12  -0.251870  0.211700 -0.438506 -0.051795 -0.136416 -0.268558 -0.141432   
13  -0.194034 -0.016352 -0.095463  0.094725 -0.298971 -0.137702 -0.001015   
14  -0.307833  0.226271  0.213757 -0.205015 -0.257759 -0.362918  0.016631   
15  -0.200516  0.220253  0.180861  0.288673 -0.250995 -0.203781 -0.126099   
16  -0.018939  0.189578  0.505721 -0.089343 -0.149445 -0.004305 -0.137203   
17  -0.159230  0.204238 -0.296537  0.255185 -0.353640 -0.173951  0.161049   
18  -0.107165  0.127607  0.008776 -0.082856 -0.271453 -0.046457  0.065060   
19  -0.211006  0.242263  0.263679  0.026574 -0.274689 -0.161862  0.045578   
20  -0.199616 -0.410147 -0.183574  0.103686 -0.136964 -0.149160 -0.072779   
21  -0.174531 -0.373329  0.458122  0.056071 -0.105093 -0.149824 -0.135635   
22  -0.082691  0.095922 -0.179301  0.298367 -0.303148 -0.069206 -0.100686   
23  -0.313969 -0.223341 -0.424492  0.138578 -0.191885 -0.289390  0.055767   
24  -0.170608  0.007406 -0.275088  0.060653 -0.242219 -0.191935  0.490247   
25  -0.247361  0.009068 -0.003184  0.097008 -0.181814 -0.252198  0.268151   
26  -0.335377  0.047501 -0.420392  0.023488 -0.297831 -0.331769  0.179685   
27  -0.276184 -0.202116 -0.038642  0.076345 -0.246872 -0.244702  0.134496   
28  -0.218004 -0.234874  0.015362 -0.516520 -0.234297 -0.242373 -0.137564   
29  -0.281967 -0.050094 -0.286606 -0.091259 -0.326868 -0.294743 -0.391839   
..        ...       ...       ...       ...       ...       ...       ...   
420  0.034464 -0.108790 -0.259179  0.125588  0.377758  0.093767 -0.241106   
421 -0.189785  0.049982  0.492628  0.167158  0.386473 -0.190747 -0.196907   
422 -0.275511 -0.133953  0.450315 -0.198962  0.329362 -0.157893  0.017001   
423  0.001949 -0.019886 -0.040946 -0.495224  0.514777 -0.050207 -0.463998   
424  0.015876  0.086050 -0.181023 -0.049520  0.341592 -0.062956 -0.191507   
425 -0.113033 -0.128388  0.395882 -0.224899  0.490805 -0.087682  0.182671   
426 -0.264944  0.067640 -0.192437  0.049752  0.375535 -0.216320  0.259290   
427 -0.136080 -0.263042 -0.269026  0.176349  0.410316 -0.101919 -0.153352   
428 -0.236094  0.097170  0.439332 -0.183037  0.488397 -0.280723 -0.018619   
429 -0.144185  0.302586 -0.479332  0.033458  0.404337 -0.179844  0.000696   
430 -0.231084  0.159321 -0.445448  0.194221  0.300761 -0.246788  0.166881   
431 -0.253058  0.111224  0.318919  0.060655  0.408036 -0.188897  0.157880   
432 -0.098127  0.072197 -0.345195 -0.018311  0.465726 -0.120775 -0.050214   
433 -0.065423  0.420994 -0.268467 -0.044324  0.429570 -0.036181  0.119649   
434 -0.034846  0.091241  0.408554  0.195832  0.399043  0.011738  0.006437   
435 -0.180742 -0.038433 -0.472524 -0.082549  0.339084 -0.196508 -0.038264   
436 -0.073256  0.181546 -0.266234 -0.244487  0.418582 -0.017483 -0.085343   
437 -0.166990  0.045004 -0.251616 -0.044523  0.413671 -0.226578 -0.162197   
438  0.001146  0.379434 -0.316201 -0.297017  0.365387  0.143499 -0.199611   
439 -0.267858 -0.022994 -0.360717  0.160784  0.405407 -0.302326 -0.083879   
440 -0.

Comparando las dos tablas, para el clasificador son importantes las variables  x1, x5, x6 y x10.

La predicción del modelo con las variables seleccionadas es la siguiente:

In [8]:
depend1=np.array(df.loc[:,"C1"], dtype=str)
depend2=np.array(df.loc[:,"C2"], dtype=str)
depend3=np.array(df.loc[:,"C3"], dtype=str)


#Ajuste de cada uno de los modelos
model1 = LogisticRegression(fit_intercept = True, C = 1e100)
mdl1 = model1.fit(indep3_new, depend1)

model2 = LogisticRegression(fit_intercept = True, C = 1e100)
mdl2 = model2.fit(indep3_new, depend2)

model3 = LogisticRegression(fit_intercept = True, C = 1e100)
mdl3 = model3.fit(indep3_new, depend3)


predicted_1 = model1.predict(indep3_new)
predicted_2 = model2.predict(indep3_new)
predicted_3 = model3.predict(indep3_new)


rend1=np.mean(depend1==predicted_1)
rend2=np.mean(depend2==predicted_2)
rend3=np.mean(depend3==predicted_3)

depend1=np.array(depend1, dtype=float)
depend2=np.array(depend2, dtype=float)
depend3=np.array(depend3, dtype=float)

#Rendimiento de cada uno de los modelos
print("Rendimiento de cada uno de los modelos:",rend1,rend2,rend3)

#Rendimiento del modelo global
print("Rendimiento del modelo global:",(depend1.sum()*rend1+depend2.sum()*rend2+depend3.sum()*rend3)/indep3_new.shape[0])

Rendimiento de cada uno de los modelos: 1.0 1.0 1.0
Rendimiento del modelo global: 1.0


# Pregunta 3

Construya un sistema clasificador usando la técnica de vecinos más próximos. Cómo podría modificar el algoritmo para detectar las variables más relevantes?

Se ajusta el modelo:

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import SelectFromModel

#Selección del directorio de trabajo
os.chdir('/home/agch2/Dropbox/Asignaturas 2017-I MIS/Aprendizaje de maquinas/machine-learning-master')

#Carga del archivo en un dataframe
df = pd.read_table("datos.csv",sep=",")

#Selección de variables independientes y dependiente (la última no es usada para calibrar el modelo sino solo para ver que tal pronostica, ya que es un algoritmo no supervisado)
indep=df.iloc[:,range(10)]
depend=np.array(df.loc[:,"class"], dtype=int)

depend = np.array(df.loc[:,"class"], dtype=str)
neigh = KNeighborsClassifier(n_neighbors=3)

neigh.fit(indep, depend)

neigh_predict=neigh.predict(indep)

#Rendimiento del modelo:
rend_neigh=np.mean(depend==neigh_predict)
rend_neigh

1.0

Con vecinos más cercanos también se obtiene un rendimiento de 100%:

Se puede observar que la predicción del modelo es de un 100%. Ahora procedemos a seleccionar las variables principales. Al igual que K-means, la función de Python de vecinos más cercanos no cuenta con una función para la selección de variables. Así, se realiza la selección de variables de la siguiente forma:

- Se aplica el algoritmo añadiendo una por una cada variable independiente. Es decir, se empieza utilizando solamente una de ellas y luego se utiliza otra, extrayendo la variable incluida anteriormente. Esto se hace sucesivamente para cada una de las variables. De todas las variables, finalmente la primera variable que se incluye en el modelo, es quella que mayor aumento genera en su rendimiento.
- El procedimiento anterior se hace repetidamente hasta que el rendimiento se estabilice.

In [10]:
rend_tot_fin=[]
S_F_tot=[]
V_S_F=range(indep.shape[1])
indep2=indep[:]


for j in range(indep.shape[1]):  #Ver como cambia el rendimiento mientras aumento una por una mis variables

    rend_tot=[]
    
    for i in V_S_F:  #Selecionar la variable que genera mayor aumento en el rendimiento de cada corrida
        
        if j==0:
            indep_F_S=indep.iloc[:,[i]]
        else:
            indep_F_S=indep.iloc[:,list(set().union(S_F_tot,[i]))]
            
        #print(list(set().union(seq1,seq2)))
        #print(indep_F_S)
        
        
        
        
        neigh = KNeighborsClassifier(n_neighbors=3)

        neigh.fit(indep_F_S, depend)

        neigh_predict=neigh.predict(indep_F_S)

        #Rendimiento del modelo:
        rend_neigh=np.mean(depend==neigh_predict)
        rend_neigh
        

        #rend_Km
        #print("%.3f" % rend_Km)

        rend_tot.append(rend_neigh)

    #print(rend_tot)
    m = max(rend_tot)
    S_F=[i for i, j in enumerate(rend_tot) if j == m]
    if j==0:
        S_F=S_F[:]
    else:
        for k in S_F_tot:
            if S_F[0]>=k:
                S_F[0]=S_F[0]+1
            else: S_F[0]=S_F[0]
    S_F_tot.append(S_F[0])
    
    seq1=list(range(indep2.shape[1]))[0:S_F[0]]
    seq2=list(range(indep2.shape[1]))[S_F[0]+1:10]
    V_S_F=list(set().union(seq1,seq2))
    indep2=indep2.iloc[:,V_S_F]
    #print(V_S_F)
    
    rend_tot_fin.append(m)

#print(rend_tot_fin)

m2 = max(rend_tot_fin)
S_F_Max=[i for i, j in enumerate(rend_tot_fin) if j == m2]

S_F_Variables=S_F_tot[0:S_F_Max[0]+1]
print("Variables seleccionadas:   ","x",S_F_Variables[0],",   x",S_F_Variables[1],"\nRendimiento:",m2)

Variables seleccionadas:    x 4 ,   x 0 
Rendimiento: 1.0


# Pregunta 4

Construya un sistema clasificador usando árboles de decisión. Ya que los árboles permiten detectar variables relevantes, las variables seleccionadas en este punto coinciden con las obtenidas en las preguntas anteriores?

In [11]:
from sklearn import tree
from sklearn.feature_selection import SelectFromModel

depend = np.array(df.loc[:,"class"], dtype=str)
treeC = tree.DecisionTreeClassifier()
treeC = treeC.fit(indep, depend)

predicted=treeC.predict(indep)
rend=np.mean(depend==predicted)

print(rend)
#print(treeC.predict(indep))
#print(treeC.predict_proba(indep))

1.0


Puede observarse que la predicción del modelo es de 100%. Ahora, se observan las variables más importantes:

In [12]:
treeC.feature_importances_

array([ 0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0.5])

Genero el modelo con las variables más importantes:

In [13]:
treeC_sf = SelectFromModel(treeC, prefit=True)
indep_treeC_new = treeC_sf.transform(indep)
indep_treeC_new

array([[ -2.80745077e-01,   4.49686781e+00],
       [  5.39491346e-01,   5.22636841e+00],
       [ -2.11045031e-01,   4.90470781e+00],
       [  2.81598929e-01,   5.42906859e+00],
       [ -5.66705821e-01,   4.78860103e+00],
       [ -3.20724736e-01,   4.03053851e+00],
       [ -7.25106368e-01,   3.95338673e+00],
       [  4.84749562e-01,   3.76981427e+00],
       [ -9.45430259e-01,   2.94467622e+00],
       [ -3.05525688e-01,   4.20046519e+00],
       [ -3.74175287e-01,   3.58469583e+00],
       [ -6.60614728e-01,   3.37249152e+00],
       [  3.96413730e-01,   4.15868567e+00],
       [ -7.20570106e-01,   3.60498869e+00],
       [ -4.37384788e-01,   2.94222910e+00],
       [ -3.90904119e-01,   3.76264235e+00],
       [  3.06888599e-01,   5.78029504e+00],
       [ -1.09621672e+00,   3.45927769e+00],
       [ -5.31482263e-01,   4.45017124e+00],
       [ -5.53718518e-01,   3.66071087e+00],
       [  3.92647128e-01,   4.64097982e+00],
       [  6.11643474e-01,   4.98200776e+00],
       [ -

In [14]:
indep

x1        x2        x3        x4        x5        x6        x7  \
0    0.217051  2.301448  2.063373 -2.877469 -0.280745  3.037343  1.523219   
1    0.245344  1.873901  2.177668 -2.907616  0.539491  3.113836  1.327698   
2    0.515188  2.052923  2.021482 -2.868717 -0.211045  3.082855  1.517711   
3    0.529766  1.793446  2.211673 -2.912831  0.281599  3.107664  1.510040   
4    0.821210  1.472261  2.057228 -2.733129 -0.566706  3.071136  1.462961   
5    0.006832  1.636809  2.006419 -3.058976 -0.320725  3.001691  1.342740   
6    0.210622  1.673330  2.118072 -2.981704 -0.725106  3.026343  1.441529   
7   -0.926146  1.261560  2.006528 -2.930952  0.484750  2.796875  1.414336   
8   -0.519451  1.875428  2.189321 -2.811001 -0.945430  2.944155  1.465402   
9    0.154951  2.140579  2.288953 -3.041501 -0.305526  3.018264  1.332776   
10  -0.302194  2.050196  2.138238 -3.014728 -0.374175  2.898792  1.362273   
11  -0.428108  1.680516  2.062366 -2.895603 -0.660615  2.915524  1.545691   
12  -0.452245  2.424376  2.016694 -3.038602  0.396414  2.877719  1.336798   
13  -0.108509  2.012992  2.119065 -2.946988 -0.720570  3.038645  1.395422   
14  -0.784852  2.450662  2.211342 -3.134406 -0.437385  2.761676  1.402790   
15  -0.147035  2.439806  2.201525 -2.825718 -0.390904  2.957382  1.343200   
16   0.932146  2.384470  2.298470 -3.062080  0.306889  3.202696  1.338564   
17   0.098343  2.410916  2.059060 -2.846657 -1.096217  2.994067  1.463084   
18   0.407787  2.272680  2.150172 -3.058024 -0.531482  3.150858  1.423009   
19  -0.209380  2.479509  2.226240 -2.989601 -0.553719  3.008934  1.414875   
20  -0.141683  1.302622  2.092771 -2.941385  0.392647  3.024554  1.365461   
21   0.007407  1.369037  2.284265 -2.971157  0.611643  3.023738  1.339219   
22   0.553244  2.215524  2.094046 -2.819657 -0.749271  3.122881  1.353810   
23  -0.821321  1.639603  2.020876 -2.919568  0.015265  2.852100  1.419129   
24   0.030722  2.055849  2.065461 -2.968292 -0.330598  2.971950  1.600525   
25  -0.425451  2.058847  2.146603 -2.945560  0.084463  2.897839  1.507799   
26  -0.948557  2.128176  2.022100 -2.991530 -0.712736  2.799983  1.470865   
27  -0.596753  1.677890  2.136021 -2.958481 -0.362574  2.907057  1.451998   
28  -0.250969  1.618797  2.152137 -3.329180 -0.276166  2.909922  1.338413   
29  -0.631126  1.952123  2.062024 -3.063278 -0.912259  2.845517  1.232254   
..        ...       ...       ...       ...       ...       ...       ...   
420  1.249536  1.846241  2.070209 -2.927690  3.929507  3.323305  1.295185   
421 -0.083256  2.132653  2.294562 -2.901698  3.989392  2.973411  1.313637   
422 -0.592756  1.800851  2.281936 -3.130621  3.596956  3.013814  1.402944   
423  1.056286  2.006616  2.135334 -3.315864  4.871020  3.146246  1.202127   
424  1.139059  2.197716  2.093532 -3.037180  3.680993  3.130567  1.315892   
425  0.372909  1.810888  2.265692 -3.146839  4.706296  3.100160  1.472112   
426 -0.529953  2.164506  2.090126 -2.975108  3.914228  2.941962  1.504100   
427  0.235931  1.567985  2.067270 -2.895951  4.153225  3.082652  1.331822   
428 -0.358486  2.217774  2.278658 -3.120664  4.689749  2.862759  1.388073   
429  0.187761  2.588326  2.004511 -2.985296  4.112142  2.986820  1.396137   
430 -0.328706  2.329890  2.014622 -2.884776  3.400428  2.904493  1.465519   
431 -0.459310  2.243127  2.242724 -2.968291  4.137557  2.975686  1.461761   
432  0.461500  2.172727  2.044540 -3.017665  4.533970  3.059462  1.374882   
433  0.655876  2.801924  2.067437 -3.033931  4.285524  3.163496  1.445800   
434  0.837600  2.207080  2.269473 -2.883769  4.075764  3.222426  1.398534   
435 -0.029511  1.973159  2.006542 -3.057832  3.663763  2.966326  1.379871   
436  0.609322  2.369980  2.068103 -3.159087  4.210023  3.186490  1.360216   
437  0.052223  2.123672  2.072466 -3.034055  4.176275  2.929346  1.328129   
438  1.051514  2.726953  2.053192 -3.191931  3.844498  3.384465  1.312509   
439 -0.547267  2.001009  2.039908 -2.905683  4.119493  2.836192  1.360827   
440 -0.

Las variables seleccionadas son x6 y x10, lo cual difiere con los anteriores modelos.

El rendimiento del modelo con las variables seleccionadas es de 100%:

In [15]:
treeC = tree.DecisionTreeClassifier()
treeC = treeC.fit(indep_treeC_new, depend)

predicted = treeC.predict(indep_treeC_new)

rend=np.mean(depend==predicted)
rend

1.0

---